# Mirrors the commits of this repo to the Epitech repo
name: Mirroring

on:
  push:
    branches:
      - main

jobs:
  to_epitech_github:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch depth set to 0 means that all commits are to be mirrored

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechMscProPromo2025/T-DEV-811-NAN_1.git
          ssh_private_key: ${{secrets.EPITECH_MIRROR_SSH_KEY}}
